name = "M4"
uuid = "2195a5f3-7642-4e25-ac27-a7b8005e7ce1"
authors = ["glebashnik <glebsv@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
